[package]
name = "sql"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/hilbert-space/sql"
homepage = "https://github.com/hilbert-space/sql"
description = "SQL."
