[package]
name = "sql"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sql"
homepage = "https://github.com/stainless-steel/sql"
description = "Structured query language."
